name: Build

on:
  push:
    branches: ["master"]
  # Runs on any open or reopened pull request
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production  # Specify the environment here
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2  # run any `bun` or `bunx` command from here

      - name: Install Dependencies
        run: bun install

      - name: Build the project
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bun run build
