name: Build

on:
  push:
    branches: ["master"]
  # Runs on any open or reopened pull request
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          node-version: 20

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run build
